In [8]:
import sys
import pandas as pd
from pathlib import Path

In [3]:
root=Path.cwd().parent
print(root)

c:\Users\USER\Desktop\data-analysis\Data-analysis

In [4]:
sys.path.append(str(root))
from src.ingestion.csv_ingestion import load_datasets

In [12]:
datasets=load_datasets()
pd.set_option('display.max_columns', None)
def analyze(name,df):
    print(f"Dataset: {name}")
    print(f"Shape: {df.shape}")
    df.info()
    display(df.head())
    print("Missing Values: ")
    display(df.isnull().sum())
    print("Summary Statistics: ")
    display(df.describe(include='all'))
    print("Unique Values: ")
    display(df.nunique())
    print("Duplicates: ", df.duplicated().sum())

In [29]:
analyze("product_category_name_translation", datasets["product_category_name_translation"])

Dataset: product_category_name_translation
Shape: (71, 2)
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Missing Values:

product_category_name            0
product_category_name_english    0
dtype: int64

Summary Statistics:

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

Unique Values:

product_category_name            71
product_category_name_english    71
dtype: int64

Duplicates:  0